baseURL = 'https://yukiya4197.github.io/hida-takayama-high-school'
languageCode = 'ja-JP'
title = 'My New Hugo Site'

[params]
	customCSS = ['css/base.css', 'css/header.css', 'css/footer.css', 'css/output.css']